version: "3"

services:
  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
    networks:
      - gateway-network
      - chirpstack-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chirpstack-application-server.entrypoints=web"
        - "traefik.http.routers.chirpstack-application-server.rule=Host(`chirpstack.uat.ding.hu`) || Host(`chirpstack.smartcitycore.io`)"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.routers.chirpstack-application-server.middlewares=redirect-to-https"
        - "traefik.http.routers.chirpstack-application-server-secure.entrypoints=websecure"
        - "traefik.http.routers.chirpstack-application-server-secure.rule=Host(`chirpstack.uat.ding.hu`) || Host(`chirpstack.smartcitycore.io`)"
        - "traefik.http.routers.chirpstack-application-server-secure.tls=true"
        - "traefik.http.routers.chirpstack-application-server-secure.tls.certresolver=le"
        - "traefik.http.routers.chirpstack-application-server-secure.service=chirpstack-application-server"
        - "traefik.http.services.chirpstack-application-server.loadbalancer.server.port=8080"
        - "traefik.docker.network=gateway-network"


  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml
    networks:
      - chirpstack-network
    ports:
      - 3001:3001
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquitto

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chirpstack-rest-api.entrypoints=web"
        - "traefik.http.routers.chirpstack-rest-api.rule=Host(`chirpstack-api.uat.ding.hu`) || Host(`chirpstack-api.smartcitycore.io`)"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.routers.chirpstack-rest-api.middlewares=redirect-to-https"
        - "traefik.http.routers.chirpstack-rest-api-secure.entrypoints=websecure"
        - "traefik.http.routers.chirpstack-rest-api-secure.rule=Host(`chirpstack-api.uat.ding.hu`) || Host(`chirpstack-api.smartcitycore.io`)"
        - "traefik.http.routers.chirpstack-rest-api-secure.tls=true"
        - "traefik.http.routers.chirpstack-rest-api-secure.tls.certresolver=le"
        - "traefik.http.routers.chirpstack-rest-api-secure.service=chirpstack-rest-api"
        - "traefik.http.services.chirpstack-rest-api.loadbalancer.server.port=8090"
        - "traefik.docker.network=gateway-network"
    depends_on:
      - chirpstack
    networks:
      - gateway-network
      - chirpstack-network

  postgres:
    image: postgres:14-alpine
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - chirpstack-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s

  redis:
    image: redis:7-alpine
    volumes:
      - chirpstack-redis:/data
    networks:
      - chirpstack-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s

  mosquitto:
    image: eclipse-mosquitto:2
    volumes: 
      - ./configuration/mosquitto/config/:/mosquitto/config/
    networks:
      - chirpstack-network

volumes:
  postgresqldata:
   chirpstack-redis:

networks:
  gateway-network:
    external: true
  chirpstack-network:
    
